# Generated by Django 4.0.6 on 2022-07-07 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_headofdepartment_hod2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cl', models.CharField(max_length=10)),
                ('present_status', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course')),
            ],
        ),
    ]
