# Generated by Django 4.0.6 on 2022-07-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_parent_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_fee_paid',
            field=models.IntegerField(null=True),
        ),
    ]
