# Generated by Django 4.0.6 on 2022-07-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_student_fee_student_student_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.TextField(default='arjun123', max_length=50),
            preserve_default=False,
        ),
    ]
